# Generated by Django 5.0.7 on 2024-07-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlescope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-is_main', '-tag'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика статьи'},
        ),
    ]
